### ISSUE TITLE
Ability to add text and generate report

### ISSUE THREAD

**Issue by shashank-sharma** [isohack/report-generator#1]
Your task is to create one function which takes any string as an argument and generate a report of the format in:

1. PDF
2. Image of any type

**Comment by Pkpratik** [comment]
so a function which takes a string parameter and generates a PDF containing the same text as the string parameter right?

**Comment by shashank-sharma** [comment]
@Pkpratik Yes

**Comment by shashank-sharma** [comment]
Fixed in #4
